package Games.XOGame.Forms;

import Helpers.DataTransfer;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;

public class InputForm extends JFrame {
    private JButton btnDone;
    private JTextField txbData;
    public JPanel MainPanel;
    private JLabel lblTitle;
    private JFrame formToShow;
    public boolean dataReady;

    public InputForm() {
        btnDone.setText("Готово");
        lblTitle.setText("Инструкия по вводу данных");
        txbData.setText("Данные");
        Init();
    }

    public InputForm(String btnTitle, String labelTitle, String dataTitle) {
        btnDone.setText(btnTitle);
        lblTitle.setText(labelTitle);
        txbData.setText(dataTitle);
        Init();
    }

    private void Init() {
        this.dataReady = false;
        AddListeners();
        add(MainPanel);
        setLocationRelativeTo(null);
        pack();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setVisible(true);
    }

    private void AddListeners() {
        btnDone.addActionListener(e -> {
            DataTransfer.StrData.data = txbData.getText();
            this.dataReady = true;
        });
    }

    public void Close() {
        this.dispose();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        MainPanel = new JPanel();
        MainPanel.setLayout(new GridLayoutManager(3, 1, new Insets(0, 0, 0, 0), -1, -1));
        lblTitle = new JLabel();
        lblTitle.setText("Label");
        MainPanel.add(lblTitle, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txbData = new JFormattedTextField();
        MainPanel.add(txbData, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        btnDone = new JButton();
        btnDone.setText("Button");
        MainPanel.add(btnDone, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return MainPanel;
    }
}
