package Games.XOGame.Forms;

import Helpers.DataTransfer;
import Helpers.Forms;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;

public class InputForm extends JFrame {
    private JButton btnDone;
    private JTextArea txbData;
    public JPanel MainPanel;
    private JLabel lblTitle;
    private JFrame frameToShow;

    public InputForm() {
        btnDone.setText("Готово");
        lblTitle.setText("Инструкия по вводу данных");
        txbData.setText("Данные");
        Init();
    }

    public InputForm(String btnTitle, String labelTitle, String dataTitle, JFrame frameToShow) {
        btnDone.setText(btnTitle);
        lblTitle.setText(labelTitle);
        txbData.setText(dataTitle);
        this.frameToShow = frameToShow;
        Init();
    }

    private void Init() {
        AddListeners();
        add(MainPanel);
        setLocationRelativeTo(null);
        pack();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setVisible(true);
    }

    private void AddListeners() {
        btnDone.addActionListener(e -> {
            DataTransfer.StrData.data = txbData.getText();
            //if (this.frameToShow != null) {
                Main mainForm = null;
                try {
                    mainForm = new Main();
                } catch (Exception e1) {
                    e1.printStackTrace();
                }
                mainForm.show();
//                Forms formsHelper = new Forms();
//                formsHelper.Show(formsHelper.Create(this.panel, ""));
           //}
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        MainPanel = new JPanel();
        MainPanel.setLayout(new GridLayoutManager(3, 2, new Insets(0, 0, 0, 0), -1, -1));
        btnDone = new JButton();
        btnDone.setText("Button");
        MainPanel.add(btnDone, new GridConstraints(2, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txbData = new JTextArea();
        MainPanel.add(txbData, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, new Dimension(150, 25), new Dimension(150, 25), null, 0, false));
        lblTitle = new JLabel();
        lblTitle.setText("Label");
        MainPanel.add(lblTitle, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return MainPanel;
    }
}
