package Games.XOGame.Forms;

import GUI_Forms.IOForm;
import GUI_Forms.InputForm;
import GUI_Forms.OutputForm;
import Games.Field.GameField;
import Games.XOGame.Core.XO;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

public class Main extends IOForm {
    private JTable tGameField;
    public JPanel MainPanel;
    private JLabel lblOutPut;
    private XO game;

    public Main() {
        try {
            InputForm in = new InputForm("Готово", "Размер поля", "");
            while (!in.GetDataReady())
                Thread.sleep(1000);
            int size = Integer.parseInt((String) in.data);
            in.Close();
            GameField field = new GameField(size);

            Out(field, tGameField);
            Init();
            this.game = new XO(size, this);
            this.game.Start();
        } catch (Exception ex) {
            new OutputForm("Ok", ex);
        }
    }

    private void Init() {
        Init(new JComponent[]{tGameField}, new JComponent[]{tGameField, lblOutPut}, MainPanel);
        AddListeners();
        add(MainPanel);
        setLocationRelativeTo(null);
        pack();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setVisible(true);
    }

    public void AddListeners() {
        tGameField.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent evt) {
                try {
                    In(tGameField);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }

            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        MainPanel = new JPanel();
        MainPanel.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1, true, false));
        tGameField = new JTable();
        MainPanel.add(tGameField, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, new Dimension(500, 500), new Dimension(500, 500), null, 0, false));
        lblOutPut = new JLabel();
        lblOutPut.setText("Label");
        MainPanel.add(lblOutPut, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return MainPanel;
    }
}
