package Games.XOGame.Forms;

import Games.Field.GameField;
import Helpers.DataTransfer;
import Helpers.IOForm;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

public class Main extends JFrame {
    private JTable tGameField;
    public JPanel MainPanel;
    private JLabel lblOutPut;

    public Main() throws Exception {
//        XO game = new XO(new IOForm());
//        game.Start();
        IOForm io = new IOForm();


        GameField field = new GameField(Integer.parseInt(DataTransfer.StrData.data));
        io.Out(field, tGameField);
//        DefaultTableModel model = new DefaultTableModel();
//        // Create a couple of columns
//        model.addColumn("Col1");
//        model.addColumn("Col2");
//        // Append a row
//        model.addRow(new Object[]{"-", "-"});
//        model.addRow(new Object[]{"-", "-"});
//        model.addRow(new Object[]{"-", "-"});
//        tGameField.setModel(model);

        Init();
    }

    private void Init() {
        AddListeners();
        add(MainPanel);
        setLocationRelativeTo(null);
        pack();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setVisible(true);
    }

    private void AddListeners() {
        tGameField.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent evt) {
                int row = tGameField.rowAtPoint(evt.getPoint());
                int col = tGameField.columnAtPoint(evt.getPoint());
                if (row >= 0 && col >= 0) {
                    System.out.println(row);
                    System.out.println(col);
                }
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        MainPanel = new JPanel();
        MainPanel.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1, true, false));
        tGameField = new JTable();
        MainPanel.add(tGameField, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, new Dimension(500, 500), new Dimension(500, 500), null, 0, false));
        lblOutPut = new JLabel();
        lblOutPut.setText("Label");
        MainPanel.add(lblOutPut, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return MainPanel;
    }
}
