package GUI_Forms;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;

public class InputForm extends IOForm {
    private JButton btnDone;
    private JTextField txbData;
    public JPanel mainPanel;
    private JLabel lblTitle;

    public InputForm() {
        btnDone.setText("Готово");
        lblTitle.setText("Инструкия по вводу данных");
        lblTitle.setText(String.format("%d", Thread.currentThread().getId()));
        txbData.setText("Данные");
        Open(mainPanel);
    }

    /**
     * @param btnTitle   текст кнопки
     * @param labelTitle инкструкция по вводу
     * @param dataTitle  текст в тектовом поле
     */
    public InputForm(String btnTitle, String labelTitle, String dataTitle) {
        btnDone.setText(btnTitle);
        lblTitle.setText(labelTitle);
        txbData.setText(dataTitle);
        Open(mainPanel);

    }

    private Runnable GetData() {
        Runnable component = () -> {
            try {
                data = In(txbData);
            } catch (InterruptedException e1) {
                e1.printStackTrace();
            }
        };
        return component;
    }

    public void AddListeners() {
        btnDone.addActionListener(e -> {
            try {
                new Thread(GetData()).start();
            } catch (Exception ex) {
                ex.printStackTrace();
            }
            SetDataReady(true);
        });
    }

    public void Close() {
        this.dispose();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(3, 1, new Insets(0, 0, 0, 0), -1, -1));
        lblTitle = new JLabel();
        lblTitle.setText("Label");
        mainPanel.add(lblTitle, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txbData = new JFormattedTextField();
        mainPanel.add(txbData, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        btnDone = new JButton();
        btnDone.setText("Button");
        mainPanel.add(btnDone, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
