package GUI_Forms;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;

public class InputForm extends IOForm {
    private JButton btnDone;
    private JTextField txbData;
    public JPanel mainPanel;
    private JLabel lblTitle;

    /**
     * данные, которые ввел пользователь
     */
    public Object data;

    public InputForm() {
        btnDone.setText("Готово");
        //lblTitle.setText("Инструкия по вводу данных");
        lblTitle.setText(String.format("%d", Thread.currentThread().getId()));
        txbData.setText("Данные");
        Open(mainPanel);
    }

    /**
     * @param btnTitle   текст кнопки
     * @param labelTitle инкструкция по вводу
     * @param dataTitle  текст в тектовом поле
     */
    public InputForm(String btnTitle, String labelTitle, String dataTitle) {
        btnDone.setText(btnTitle);
        lblTitle.setText(labelTitle);
        txbData.setText(dataTitle);
        Open(mainPanel);
    }

    public void AddListeners() {
        btnDone.addActionListener(e -> {
            try {
                //DataTransfer.StrData.data = (String) In("");
                data = In(txbData);
            } catch (Exception ex) {
                ex.printStackTrace();
            }
            SetDataReady(true);
        });
    }

    public void Close() {
        this.dispose();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(3, 1, new Insets(0, 0, 0, 0), -1, -1));
        lblTitle = new JLabel();
        lblTitle.setText("Label");
        mainPanel.add(lblTitle, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txbData = new JFormattedTextField();
        mainPanel.add(txbData, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        btnDone = new JButton();
        btnDone.setText("Button");
        mainPanel.add(btnDone, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
