package GUI_Forms;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;

public class OutputForm<T> extends IOForm {
    private JButton btnOK;
    private JLabel lblData;
    private JPanel mainPanel;

    public OutputForm() {
        Open(mainPanel);
    }

    /**
     * создает окно для отображения информации
     *
     * @param btnTitle подпись кнопки
     * @param data     данные на вывод
     */
    public OutputForm(String btnTitle, T data) {
        btnOK.setText(btnTitle);
        lblData.setText(data.toString());
        btnOK.setText(btnTitle);
        Open(mainPanel);
    }

    /**
     * привязывает обработчики кнопок
     */
    public void AddListeners() {
        btnOK.addActionListener(e -> this.dispose());
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        lblData = new JLabel();
        lblData.setText("Label");
        mainPanel.add(lblData, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnOK = new JButton();
        btnOK.setText("Button");
        mainPanel.add(btnOK, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}